services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
    - SPRING_DATASOURCE_URL=${DB_URL}
    - SPRING_DATASOURCE_USERNAME=${DB_USER}
    - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    - tmdb.api.key=${TMDB_API_KEY}
    - jwt.secret=${JWT_SECRET}
    - jwt.expiration=${JWT_EXPIRATION}
    - springdoc.swagger-ui.enabled=true
    - springdoc.api-docs.enabled=true