spring.application.name=tv-and-movie-db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
tmdb.api.key=${tmdb.api.key}
jwt.secret=${jwt.secret}
jwt.expiration=${jwt.expiration}